// Generates the reference pages in docs/reference/ from the code, so they can't drift out of date.
// Usage: npm run docs:build   (write the pages)
//        npm run docs:check   (exit 1 if a page is out of date; also run by the tests)
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';

const root = new URL('../', import.meta.url);
const src = p => new URL(`public/src/${p}`, root);
const HEADER = '<!-- Generated by tools/docs.mjs from the code. Do not edit by hand: run `npm run docs:build`. -->\n\n';
const table = (head, rows) => [`| ${head.join(' | ')} |`, `|${head.map(() => '---').join('|')}|`, ...rows.map(r => `| ${r.join(' | ')} |`)].join('\n');
const list = obj => Object.entries(obj).map(([k, v]) => `${v} ${k}`).join(', ');

async function effectsPage() {
  await import(src('effects/index.js').href);
  const { effectDocs } = await import(src('effects/registry.js').href);
  const lines = effectDocs().split('\n');
  const rows = lines.filter(l => l.startsWith('{')).map(l => {
    const [, json, note] = l.match(/^(\{.*?\}(?: \/ \{.*?\})?)\s{2,}(.*)$/) || [null, l, ''];
    const types = [...json.matchAll(/"type":"(\w+)"/g)].map(m => `\`${m[1]}\``).join(', ');
    return [types, `\`${json.replaceAll('|', '\\|')}\``, note.replaceAll('|', '\\|')];
  });
  return `# Effect types

Inventions, custom possibilities and activities are made only of these effects. The text model that
invents ideas is given the same list. Code validates every effect and clamps its numbers to the ranges below
(see \`public/src/effects/registry.js\`).

"who" is \`self\`, \`target\` or \`everyone_near\`.

${table(['Type', 'Example', 'Notes'], rows)}

An invention can also have a skill check: \`"check":{"skill":"crafting","difficulty":"easy|normal|hard"}\`
with \`"fail_effects":[...]\` for when it fails.
`;
}

async function verbsPage() {
  const { VERBS } = await import(src('actions/registry.js').href);
  const sections = [];
  for (const file of ['basic', 'social', 'work', 'civic', 'crime']) {
    const before = new Set(Object.keys(VERBS));
    await import(src(`actions/verbs/${file}.js`).href);
    const added = Object.keys(VERBS).filter(k => !before.has(k));
    const about = readFileSync(src(`actions/verbs/${file}.js`), 'utf8').split(/\r?\n/)[0].replace(/^\/\/\s*/, '');
    sections.push(`## ${file}.js\n\n${about}\n\n${added.map(v => `\`${v}\``).join(', ')}`);
  }
  return `# Verbs

Every action a person can take has a \`type\`, handled by a verb registered with \`defineVerbs()\`
in \`public/src/actions/verbs/\`. Unknown types fall back to \`default\`.

${sections.join('\n\n')}
`;
}

async function worldPage() {
  const d = async p => import(src(`data/${p}.js`).href);
  const [{ DEFAULT_PLACES }, { DEFAULT_NPCS }, { SKILLS, ADULT_ROLES }, eco, civic] =
    await Promise.all([d('map'), d('people'), d('skills'), d('economy'), d('civic')]);
  const places = DEFAULT_PLACES.map(p => [p.name, p.type, p.res ? `${p.res.item} (${p.res.skill})` : '', p.owner || '']);
  const people = DEFAULT_NPCS.map(n => [n.name, n.age, n.role, n.pronouns, n.home || '']);
  const builds = eco.BUILDABLES.map(b => [b.name, b.kind, list(b.cost)]);
  const biz = Object.entries(eco.BUSINESS_TYPES).map(([k, b]) => [k, b.skill, list(b.in) || '-', list(b.out) || '-']);
  const problems = Object.values(civic.PROBLEM_TYPES).map(p => [p.title, p.skill, p.place || '']);
  return `# World data

The starting world, from \`public/src/data/\`. Edit those files to change it.

## Places (\`map.js\`)

${table(['Name', 'Type', 'Resource', 'Owner'], places)}

## People (\`people.js\`)

${table(['Name', 'Age', 'Role', 'Pronouns', 'Home'], people)}

## Skills and roles (\`skills.js\`)

Skills: ${SKILLS.join(', ')}.

Roles chosen at coming of age: ${ADULT_ROLES.join(', ')}.

## Things people can build (\`economy.js\`)

${table(['Name', 'Kind', 'Cost'], builds)}

## Businesses (\`economy.js\`)

${table(['Kind', 'Skill', 'Uses', 'Makes'], biz)}

Base prices: ${list(Object.fromEntries(Object.entries(eco.BASE_PRICES).map(([k, v]) => [k, `${v}c`]))).replace(/(\d+c) (\w+)/g, '$2 $1')}.

## Laws a leader can decree (\`civic.js\`)

${table(['Key', 'Law'], Object.entries(civic.DECREES).map(([k, v]) => [`\`${k}\``, v]))}

## Problems (\`civic.js\`)

${table(['Title', 'Skill', 'Place'], problems)}
`;
}

globalThis.performance ??= { now: () => 0 };
const pages = { 'effects.md': await effectsPage(), 'verbs.md': await verbsPage(), 'world.md': await worldPage() };
const dir = new URL('docs/reference/', root);
const check = process.argv.includes('--check');
const stale = [];
mkdirSync(dir, { recursive: true });
for (const [name, body] of Object.entries(pages)) {
  const file = new URL(name, dir);
  // Format like `npm run format:md` would, so the Markdown check and this check agree.
  const path = fileURLToPath(file);
  const text = await prettier.format(HEADER + body, { ...(await prettier.resolveConfig(path)), filepath: path });
  let old = null;
  try { old = readFileSync(file, 'utf8').replace(/\r\n/g, '\n'); } catch { /* new page */ }
  if (old === text) continue;
  if (check) stale.push(name);
  else { writeFileSync(file, text); console.log(`wrote docs/reference/${name}`); }
}
if (stale.length) { console.error(`Out of date: ${stale.join(', ')}. Run: npm run docs:build`); process.exit(1); }
if (check) console.log('✓ generated docs are up to date');
